#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — Note-Pilot redeploy (portfolio-site ticket 11).
#
# Target: a fresh Neon Postgres database Newton administers, an OpenRouter
# key for the AI features, and a live Vercel deployment with both wired in.
# See NewtonProfile/.scratch/portfolio-site/issues/11-note-pilot-redeploy.md
# and CONTEXT.md's "Note-Pilot deployment" section for full background.
# ──────────────────────────────────────────────────────────────────────────

REPO_DIR="/c/Users/sageb/Documents/Projects/Note_Pilot"
ENV_FILE="$REPO_DIR/.env"
NOTE_PILOT_URL=""

TOTAL_STAGES=5

banner "Note-Pilot redeploy"

# ── Stage 1: Neon — Postgres database ──────────────────────────────────────
stage "Neon — create the Postgres database"
say "Note-Pilot's prisma/schema.prisma expects two connection strings:"
say "  DATABASE_URL — pooled, used by the running app"
say "  DIRECT_URL   — unpooled, used for migrations"
say "Both come from the same Neon project; Neon shows both on request."
open_url "https://console.neon.tech/app/projects"
step "Sign up / log in, then 'New Project'. Name it e.g. 'note-pilot', pick"
step "any region, and create it — the free tier needs no card."
step "On the project dashboard's Connection Details panel, make sure the"
step "'Pooled connection' toggle is ON, and copy that connection string."
ask_secret DATABASE_URL "Paste the POOLED connection string (DATABASE_URL):"
step "Now flip 'Pooled connection' OFF on the same panel — the string"
step "changes (no '-pooler' in the hostname). Copy that one too."
note "(If Neon's UI has moved the pooled/direct toggle since this was"
note "written, look for two connection-string variants on the same panel —"
note "one with '-pooler' in the hostname, one without.)"
ask_secret DIRECT_URL "Paste the DIRECT (unpooled) connection string (DIRECT_URL):"
write_env DATABASE_URL "$DATABASE_URL"
write_env DIRECT_URL "$DIRECT_URL"
note "Both written to $ENV_FILE — this file is already gitignored."

# ── Stage 2: OpenRouter — AI API key ────────────────────────────────────────
stage "OpenRouter — API key for the AI features"
say "The code reads this as NVIDIA_AI_API but it's an OpenRouter key — it"
say "authenticates against OpenRouter's API (see src/app/api/*/route.ts),"
say "targeting the free-tier nvidia/nemotron-nano-9b-v2:free model."
open_url "https://openrouter.ai/keys"
step "Sign up / log in, click 'Create Key', name it (e.g. 'note-pilot'),"
step "and copy the key — OpenRouter only shows it once."
ask_secret NVIDIA_AI_API "Paste the OpenRouter API key (NVIDIA_AI_API):"
write_env NVIDIA_AI_API "$NVIDIA_AI_API"

# ── Stage 3: initial Prisma migration ───────────────────────────────────────
stage "Run the initial migration against the new database"
say "No prisma/migrations folder exists yet in this repo, so 'migrate dev'"
say "will create it and apply the schema to the Neon database above."
say "This writes real tables to that database — irreversible in the sense"
say "that it's the live schema init, though it's a brand-new empty DB."
cd "$REPO_DIR"
if [[ ! -d node_modules ]]; then
  if confirm "node_modules is missing — run 'npm install' now?"; then
    npm install
  else
    warn "skipping install — 'prisma migrate dev' below will likely fail."
  fi
fi
if confirm "Run 'npx prisma migrate dev --name init' against the Neon DB now?"; then
  npx prisma migrate dev --name init
  note "Migration applied and committed to prisma/migrations/ in this repo."
else
  SKIPPED+=("prisma migrate dev --name init (run manually from $REPO_DIR)")
  warn "skipped — run it yourself before deploying, or the app will 500 on any query."
fi

# ── Stage 4: deploy to Vercel ────────────────────────────────────────────────
stage "Deploy to Vercel"
say "Importing straight from GitHub gives you auto-deploys on every push to"
say "main, which is the standard path for a Next.js app — no CLI needed."
open_url "https://vercel.com/new"
step "Log in, then 'Import Git Repository' and pick NewtonSythong/Note-Pilot"
step "(github.com/NewtonSythong/Note-Pilot). Framework preset auto-detects"
step "as Next.js — leave the build settings as-is."
step "Before clicking Deploy, expand 'Environment Variables' and add all"
step "three below (paste the same values you just captured):"
note "  DATABASE_URL = ${DATABASE_URL:0:20}...(hidden)"
note "  DIRECT_URL   = ${DIRECT_URL:0:20}...(hidden)"
note "  NVIDIA_AI_API = ${NVIDIA_AI_API:0:12}...(hidden)"
step "Click Deploy and wait for the build to finish."
ask NOTE_PILOT_URL "Paste the live production URL Vercel gives you:"
note "Add this to NewtonProfile/src/content/projects/note-pilot.md as"
note "liveDemoUrl once you've confirmed it works in the next stage — that's"
note "the ticket 10 follow-up edit this unblocks."

# ── Stage 5: confirm the AI feature actually works ──────────────────────────
stage "Verify the live deployment"
if [[ -n "$NOTE_PILOT_URL" ]]; then
  open_url "$NOTE_PILOT_URL"
fi
step "Sign up for an account, upload a document (PDF), and open its paper"
step "view page."
step "Try the AI chat and one study-guide feature (flashcards or summary)"
step "and confirm you get a real response, not an error."
if ! confirm "Did the AI chat / study-guide feature respond correctly?"; then
  warn "If it failed: double-check NVIDIA_AI_API is set exactly right in"
  warn "Vercel's Project Settings → Environment Variables (redeploy after"
  warn "changing it — env var edits don't apply to already-built deploys)."
  SKIPPED+=("confirm AI chat/study-guide feature works on $NOTE_PILOT_URL")
fi
# ──────────────────────────────────────────────────────────────────────────

finish

if [[ -n "$NOTE_PILOT_URL" ]]; then
  printf '  %sLive URL:%s %s\n\n' "$BOLD" "$RESET" "$NOTE_PILOT_URL"
fi
